Validate with selenium grid

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -15,6 +15,8 @@ env:
     - secure: q9IckmvMBEEQ6EeM4U8K4y96Lx6tEaxs/A5GYUJxNJVhUkx3YqJKeERArZc4fpoV3CtUCFPDs/tktiFJn1LDeh3s9vJitUAGMU2AQxiUNARXK4EkEdPhvbX+CtusIIKDXYwEqXLiymv6mmpcc9/19CvHUzr9CiKZbb/LpS8lWqc=
     - secure: cZKPTfU0h4rH2IIRr1Ds1XRPDrloe/K+menYm+VK54hE4MM2zTtNDmWn0fyPdeHeJDRrTF0pyobje8RG9E2Ld5YPHXve1/lVkieoPeqzm9V8hlvZlkgTQJiMAvKzjhSlUJx8AKPjX+jQZfhgAS1hnuWwOIB1cAA7fMpPJ7rPVWo=
 
+services:
+  - docker
 matrix:
   include:
     - perl: '5.26'
@@ -25,7 +27,8 @@ matrix:
           packages:
             - nginx postgresql-9.6-pgtap
       env:
-        - TEST_SAUCE=1
+        - POD_TESTING=1
+        - BROWSER=chrome
     - perl: '5.24'
       addons:
         postgresql: '9.5'
@@ -44,6 +47,7 @@ matrix:
             - nginx postgresql-9.4-pgtap
       env:
         - COVERAGE=1
+        - BROWSER=phantomjs
     - perl: '5.20'
       addons:
         postgresql: "9.4"
@@ -52,6 +56,7 @@ matrix:
             - nginx postgresql-9.4-pgtap
       env:
         - COA_TESTING=1
+        - BROWSER=firefox
     - perl: '5.18'
       addons:
         postgresql: "9.3"
@@ -60,7 +65,7 @@ matrix:
             - nginx postgresql-9.3-pgtap
       env:
         - DB_TESTING=1
-        - POD_TESTING=1
+        - BROWSER=chrome
     - perl: '5.16'
       addons:
         postgresql: "9.2"
@@ -69,6 +74,7 @@ matrix:
             - nginx postgresql-9.2-pgtap
       env:
         - DB_TESTING=1
+        - BROWSER=firefox
     - perl: '5.14'
       addons:
         postgresql: "9.2"
@@ -77,6 +83,7 @@ matrix:
             - nginx postgresql-9.2-pgtap
       env:
         - DB_TESTING=1
+        - BROWSER=phantomjs
 
 before_cache:
   - mkdir -p $HOME/dojo_archive
@@ -94,18 +101,26 @@ before_install:
   - utils/diagnostics/t/01-system-resources.t
   - source /opt/jdk_switcher/jdk_switcher.sh
   - jdk_switcher use oraclejdk8
-  - phantomjs --version
-  - export PATH=$HOME/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
-  - phantomjs --version
-  - if [ $(phantomjs --version) != '2.1.1' ];
-    then
-      rm -rf $HOME/travis_phantomjs ;
-      mkdir -p $HOME/travis_phantomjs ;
-      wget https://efficito.com/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $HOME/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 ;
-      tar -xvf $HOME/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $HOME/travis_phantomjs ;
-      hash -r ;
-      phantomjs --version ;
-    fi
+  # Hub
+  - docker run
+           --detach=true
+           --name=selenium-hub
+           --publish=127.0.0.1:4422:4444
+           --volume=/dev/shm:/dev/shm
+           --volume=/dev/urandom:/dev/random
+           --privileged selenium/hub
+  # Headless browser
+  - docker run
+           --detach=true
+           --name=selenium-node-${BROWSER}
+           --link=selenium-hub:hub
+           --volume=/dev/shm:/dev/shm
+           --volume=/dev/urandom:/dev/random
+           --env=HUB_PORT_4444_TCP_ADDR=hub
+           --env=HUB_PORT_4444_TCP_PORT=4444
+           selenium/node-${BROWSER}
+  #
+  - IP=$(ifconfig | grep -A 1 'eth0' | tail -1 | cut -d ':' -f 2 | cut -d ' ' -f 1)
   - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
   - source ~/travis-perl-helpers/init
   - build-perl 2>/dev/null
@@ -134,8 +149,8 @@ before_script:
   - coverage-setup 2>/dev/null
   - export DEVEL_COVER_OPTIONS=+ignore,"\.lttc\$"
   - sed -e "s#{ROOT}#$PWD#" conf/nginx-travis.conf >/tmp/nginx.conf
-  - ((phantomjs --webdriver=4422 2>/dev/null >/dev/null &) && echo "PhantomJS started succesfully") || (echo "Failed to start PhantomJS!" ; exit 1)
-  - #PERL5OPT="$PERL5OPT $HARNESS_PERL_SWITCHES" plackup -Ilib --port 5001 --server HTTP::Server::PSGI tools/starman.psgi >/dev/null 2>/dev/null &
+  - (( $(docker inspect --format '{{ .State.Status }}' selenium-hub) == "running" &) && echo "Browser Grid started succesfully") || (echo "Failed to start Browser Grid!" ; exit 1)
+  - (( $(docker inspect --format '{{ .State.Status }}' selenium-node-${BROWSER}) == "running" &) && echo "Browser started succesfully") || (echo "Failed to start Browser!" ; exit 1)
   - PERL5OPT="$PERL5OPT $HARNESS_PERL_SWITCHES" plackup -Ilib --port 5001 --server HTTP::Server::PSGI tools/starman.psgi --access_log /tmp/plackup-access.log 2> /tmp/plackup-error.log &
   - #sleep 5  # give starman a chance to start # we now have better handling for this in Is_LSMB_running.sh
   - utils/test/Is_LSMB_running.sh --early # fail early if starman is not running (can be skipped based on reponame or owner by setting an array in the script)
@@ -143,13 +158,13 @@ before_script:
   - if [ "${DOJO_BUILT}" != "" ]; then sed -i -e "s#dojo_built *= *(\d)+#dojo_built={dojo_built}#" ledgersmb.conf ; fi
   # display the available resources
   - utils/diagnostics/t/01-system-resources.t
-  - which node
 
 script:
   - RELEASE_TESTING=1
+     BROWSER=${BROWSER}
      PGUSER=postgres PGPASSWORD=test
      LSMB_TEST_DB=1 LSMB_NEW_DB=lsmbinstalltest
-     LSMB_BASE_URL="http://127.0.0.1:5000"
+     LSMB_BASE_URL="http://${IP}:5000"
      HARNESS_RULESFILE="t/testrules.yml"
     prove -j9 -r
           --pgtap-option dbname=lsmbinstalltest
@@ -158,8 +173,7 @@ script:
           t/ xt/
 
 after_success:
-  - >
-    if [ "$COVERAGE" != "0" ] ; then
+  - if [ "$COVERAGE" != "0" ] ; then
        curl http://localhost:5001/stop.pl ;
        while [ -n "$(jobs -r | grep starman.psgi)" ] ; do sleep 1; echo -n "." ; done ;
        echo "" ;
@@ -179,3 +193,5 @@ after_failure:
   - utils/diagnostics/t/01-system-resources.t
   # display the dmesg log. may give some hints about system related failures. eg: has the OOM killer triggered
   - sudo dmesg
+  - docker logs selenium-hub
+  - docker logs selenium-node-${BROWSER}
