* Publish release artifacts to GitHub (as a trampoline for Docker Hub downlolads)

diff --git a/utils/release/release-ledgersmb b/utils/release/release-ledgersmb
--- a/utils/release/release-ledgersmb
+++ b/utils/release/release-ledgersmb
@@ -5,6 +5,7 @@ typeset -u tag_release
 
 URL="git@github.com:ledgersmb/LedgerSMB.git"
 URL_docker="git@github.com:ledgersmb/ledgersmb-docker.git"
+GH_api="https://api.github.com/repos"
 #URL=/home/ehuelsmann/releases/lsmb-repo-2
 branch="$1"
 release_version="$2"
@@ -16,6 +17,15 @@ frs_prj_dir="/home/frs/project/l/le/ledger-smb/"
 frs_tagged_dir="Releases"
 frs_untagged_dir="Beta Releases"
 tag_release="Y"
+
+if [[ ! -f ~/.lsmb-github-releases ]]; then
+   fail "Missing configuration file ~/.lsmb-github-releases!"
+else
+   source ~/.lsmb-github-releases
+
+   [[ -n "$github_user" ]] || fail "variable 'github_user' not defined! please define in ~/.lsmb-github-releases"
+   [[ -n "$github_token" ]] || fail "variable 'github_token' not defined! please define in ~/.lsmb-github-releases"
+fi
 
 if [[ -n $(echo "$release_version" | grep -- "-") ]]; then
    echo "Version modifier detected (rc/beta/...).
@@ -59,6 +69,8 @@ verify_dependencies() {
    verify_dependency "make"
    verify_dependency "msgmerge"
    verify_dependency "msguniq"
+   verify_dependency "curl"
+   verify_dependency "jq"
 }
 
 verify_release_key() {
@@ -209,7 +221,7 @@ update_docker_remote() {
    || fail "Failed to update remote docker repository!"
 }
 
-publish_files() {
+publish_files_sf() {
    (cd "$our_workspace" && \
     echo "cd '$frs_prj_dir/$prj_sub_dir'
 mkdir '$release_version'
@@ -218,6 +230,24 @@ put 'ledgersmb-$release_version.tar.gz.asc'
 put 'ledgersmb-$release_version.tar.gz'
 " | $sftp -b - "${sf_user}@frs.sourceforge.net") \
    || fail "Failed to upload files to sourceforge!"
+}
+
+publish_files_gh() {
+   gh_auth=-u "$github_user:$github_token"
+   (cd "$our_workspace" && \
+    $curl -X POST $gh_auth "$GH_api/ledgersmb/LedgerSMB/releases" \
+          -d "{'tag_name': '$release_version', 'draft': false, 'body': 'todo'}" \
+       > release_create_response)
+   || fail "Failed to create GitHub release!"
+   upload_url=$($jq -M -r '.upload_url' < $our_workspace/release_create_response | $sed -e 's/{.*//')
+   $curl -X POST -H 'Content-Type: text/plain' $gh_auth \
+         "$upload_url?name=ledgersmb-$release_version.tar.gz.asc" \
+         -T $our_workspace/ledgersmb-$release_version.tar.gz.asc \
+   || fail "Failed to upload signature file to GitHub!"
+   $curl -X POST -H 'Content-Type: application/x-tar' $gh_auth \
+         "$upload_url?name=ledgersmb-$release_version.tar.gz" \
+         -T $our_workspace/ledgersmb-$release_version.tar.gz \
+   || fail "Failed to upload tarball to GitHub!"
 }
 
 
@@ -296,12 +326,14 @@ fi
 if [[ "$tag_release" == "Y" ]]; then
    # if we don't have a release tag, be sure to discard it!
    update_remote
-   update_docker_remote
    prj_sub_dir="$frs_tagged_dir"
 else
    prj_sub_dir="$frs_untagged_dir"
 fi
-publish_files
+publish_files_sf
+publish_files_gh
+# only after we published to GH, update the docker files so they can download
+update_docker_remote
 
 extract_changelog
 extract_sha256sum
