* Update release script to fix 1.5.8 release problems
[skip ci]

diff --git a/utils/release/release-ledgersmb b/utils/release/release-ledgersmb
--- a/utils/release/release-ledgersmb
+++ b/utils/release/release-ledgersmb
@@ -14,6 +14,9 @@ new_dev_version="$3"
 sf_user="$4"
 checkout_dir="LedgerSMB"
 release_key="8DA0AF10"
+dl_base_dir="f/"
+dl_tagged_dir="Releases"
+dl_untagged_dir="Beta Releases"
 tag_release="Y"
 
 if [[ ! -f ~/.lsmb-github-releases ]]; then
@@ -218,6 +221,17 @@ update_docker_remote() {
    || fail "Failed to update remote docker repository!"
 }
 
+publish_files_dl() {
+    (cd "$our_workspace" && \
+     echo "cd '$dl_base_dir/$dl_sub_dir'
+mkdir '$release_version'
+cd '$release_version'
+put 'ledgersmb-$release_version.tar.gz.asc'
+put 'ledgersmb-$release_version.tar.gz'
+" | $sftp -b - "lsmb-uploader@download.ledgersmb.org") \
+     || fail "Failed to upload files to dl.ledgersmb.org!"
+}
+
 publish_files_gh() {
    gh_auth="-u $github_user:$github_token"
    (cd "$our_workspace" && \
@@ -317,9 +331,22 @@ if [[ "$yn" != "Y" ]]; then
    fail "Aborted by user!"
 fi
 
-publish_files_gh
-# only after we published to GH, update the docker files so they can download
+if [[ "$tag_release" == "Y" ]]; then
+    # if we don't have a release tag, be sure to discard it!
+    update_remote
+    prj_sub_dir="$dl_tagged_dir"
+else
+    prj_sub_dir="$dl_untagged_dir"
+fi
+prj_url_dir=$(echo "$prj_sub_dir" | sed -e 's/ /%20/g')
+                                                                                # only after we published to GH, update the docker files so they can download
+publish_files_dl
 update_docker_remote
+
+if [[ "$tag_release" == "Y" ]]; then
+    # we can't upload to GitHub if there's no tag...
+    publish_files_gh
+fi
 
 clear
 echo "
@@ -337,6 +364,9 @@ $extracted_changelog
 
 For installation instructions and system requirements, see
   https://github.com/ledgersmb/LedgerSMB/blob/$release_version/README.md
+
+The release can be downloaded from our download site at
+  http://download.ledgersmb.org/$dl_base_dir/$prj_url_dir/$release_version
 
 The release can be downloaded from GitHub at
   https://github.com/ledgersmb/LedgerSMB/releases/tag/$release_version
@@ -356,12 +386,9 @@ All automated steps completed.
 
 Please execute the following steps manually:
 
- * Update the latest/default download version on SourceForge
-   [put link here]
  * Update the latest version on Wikipedia
    - https://en.wikipedia.org/w/index.php?title=LedgerSMB&action=edit
    - https://es.wikipedia.org/w/index.php?title=LedgerSMB&action=edit
- * Publish a release on GitHub by converting the tag
  * Send out the release announcement to
    - ledger-smb-announce@lists.sourceforge.net
    - ledger-smb-users@lists.sourceforge.net
